### ISSUE TITLE
Non-deterministic resolution

### ISSUE THREAD

**Issue by barneycarroll** [lastmjs/zwitterion#141]
I gather that zwitterion is built with first class support for TypeScript, but I have a couple of issues with [this part of the documentation](https://github.com/lastmjs/zwitterion#es-modules):

>Or from a non-html file (if you leave out the file extension it will be assumed to be a TypeScript file):
>```js
>import {amazingFunction} from './amazing-module';
>```

As a non-TS user, this isn't intuitive to me. Would it be possible instead to offer a mode that doesn't assume TypeScript, and instead uses `require.resolve`, or similar? The idea being that the above could try for
```
./amazing-module/package.json => "module" || "main"
./amazing-module(.mjs || .ts || etc)
./amazing-module/index(.mjs || .ts || etc)
```

**Comment by lastmjs** [comment]
I'm so sorry, I don't know why I never saw this. Yes, this has been a point of annoyance and confusion for me for a while...I'm still considering exactly what should be done here. With recent developments with .mjs, certain TypeScript issues that are open, and Deno, I'm hoping to gain some clarity. I'll keep your consideration in mind of course, I've thought a lot about this in the past

**Comment by lastmjs** [comment]
I'm really glad you've found Zwitterion useful! Hopefully I can get to updating it more, but for now it's serving my needs and I don't have too much time to dig in again, trying to build some startups :) Hopefully I'll be able to find the time again soon.

**Comment by lastmjs** [comment]
I've removed that part of the documentation, I think it's confusing and misleading. If you omit the extension, Zwitterion does essentially what you suggested, it will start looking for files with an explicit extension in a deterministic order. The order is shown here: https://github.com/lastmjs/zwitterion/blob/master/src/babel-plugins/babel-plugin-transform-resolve-import-path-extensions.js

The TypeScript compiler is used to compile all .js, .mjs, and .ts files, but that shouldn't matter to you as a user because the output is JS. Reopen if you have concerns about this

**Comment by lastmjs** [comment]
Also I encourage using explicit file extensions everywhere possible, I believe in the philosophy that Deno.js promotes (explicit file extensions)
