### ISSUE TITLE
Consider creating a Caddy plugin

### ISSUE THREAD

**Issue by lastmjs** [lastmjs/zwitterion#73]
Since Caddy is extremely popular, pushing this paradigm out through a Caddy plugin might help it become mainstream. @mholt

**Comment by lastmjs** [comment]
Some interesting thoughts on this...how popular is Caddy amongst TypeScript developers and front-end web developers in general (React, Angular, Vue users, etc)? How can I use the TypeScript compiler from within Go?

**Comment by mholt** [comment]
There's a good chance you'll have to run the TypeScript compiler externally using Go's [os/exec](https://golang.org/pkg/os/exec) package. The git and hugo plugins are like this: you need git or hugo installed on your system in order to use them. That's reasonable, given that not everything Caddy integrates with is written in Go, and it still allows cross-compilation by avoiding cgo.

**Comment by lastmjs** [comment]
I don't think this is a good idea for now
